// <auto-generated/>

global using global::Microsoft.EntityFrameworkCore;
global using global::Microsoft.EntityFrameworkCore.Metadata.Builders;
global using global::Microsoft.Extensions.DependencyInjection;
global using global::Microsoft.Extensions.Logging;
global using global::System;
global using global::System.Collections.Generic;
global using global::System.Linq;
global using global::System.Linq.Expressions;
global using global::XploringMe.Core.Enumerations;
global using global::XploringMe.Core.Models.Entities.Audits;
global using global::XploringMe.Core.Models.Entities.Counters;
global using global::XploringMe.Core.Models.Entities.Enquiries;
global using global::XploringMe.Core.Models.Entities.Finance.Budgets;
global using global::XploringMe.Core.Models.Entities.Finance.Categories;
global using global::XploringMe.Core.Models.Entities.Finance.Tags;
global using global::XploringMe.Core.Models.Entities.Finance.Transactions;
global using global::XploringMe.Core.Models.Entities.Users;
global using global::XploringMe.Core.Models.Errors;
